Repository chStaiger/iBridges-Gui, pull requests merged in 2023-05, with the labels that each got.

#86 [85] Allow independent backend session
  README.md
  gui/IrodsBrowser.py
  gui/continousUpload.py
  gui/dataTransfer.py
  gui/elabUpload.py
  gui/mainmenu.py
  iBridges.py
  irodsConnector/Icommands.py
  irodsConnector/dataOperations.py
  irodsConnector/manager.py
  irodsConnector/meta.py
  irodsConnector/permission.py
  irodsConnector/query.py
  irodsConnector/resource.py
  irodsConnector/rules.py
  irodsConnector/session.py
  irodsConnector/tickets.py
  irodsConnector/users.py
  utils/context.py
  utils/json_config.py
  utils/path.py
  utils/utils.py
Labels: documentation, enhancement

#97 [96] Fix print to logging bugs
  gui/IrodsBrowser.py
  gui/amberWorkflow.py
  gui/continousUpload.py
  gui/dataTransfer.py
  gui/elabUpload.py
  gui/irodsSearch.py
  gui/irodsTicketLogin.py
  gui/irodsTreeView.py
  gui/mainmenu.py
  gui/popupWidgets.py
  iBridges.py
  iBridgesCli.py
  irodsConnector/AnonymousManager.py
  irodsConnector/Icommands.py
  irodsConnector/dataOperations.py
  irodsConnector/manager.py
  irodsConnector/meta.py
  irodsConnector/permission.py
  irodsConnector/resource.py
  irodsConnector/rules.py
  irodsConnector/session.py
  irodsConnector/tickets.py
  utils/context.py
  utils/elab_plugin.py
  utils/path.py
  utils/utils.py
Labels: bug

#104 bugfix meta class not instantiated in manager
  irodsConnector/manager.py
Labels: bug

#109 [108] Unify logging initialization
  iBridges.py
  iBridgesCli.py
  utils/utils.py
Labels: enhancement

#105 [103] Connectors issues
  iBridges.py
  irodsConnector/Icommands.py
  irodsConnector/manager.py
  irodsConnector/resource.py
  irodsConnector/tickets.py
  utils/utils.py
Labels: bug, enhancement
